In [2]:
import pandas as pd

In [5]:
df= pd.read_csv('../data/Crimes_-_2001_to_Present_20260406.csv')

In [6]:
df.shape

(544114, 22)

In [7]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14151264,JK198186,03/28/2026 12:00:00 AM,026XX N EMMETT ST,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,...,35.0,22.0,06,1154412.0,1917923.0,2026,04/04/2026 03:58:05 PM,41.930605,-87.707987,"(41.930605381, -87.707987093)"
1,14150705,JK197983,03/28/2026 12:00:00 AM,026XX E 78TH ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,7.0,43.0,14,1194996.0,1853754.0,2026,04/04/2026 03:58:05 PM,41.753614,-87.560973,"(41.753614382, -87.560973062)"
2,14154257,JK202214,03/28/2026 12:00:00 AM,011XX S CENTRAL PARK AVE,0498,BATTERY,"AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SE...",APARTMENT,False,True,...,24.0,29.0,04B,1152552.0,1894695.0,2026,04/04/2026 03:58:05 PM,41.866903,-87.715437,"(41.866902523, -87.715436986)"
3,14150115,JK197373,03/28/2026 12:00:00 AM,006XX E 40TH ST,0920,MOTOR VEHICLE THEFT,ATTEMPT - AUTOMOBILE,STREET,False,False,...,4.0,38.0,07,1181163.0,1878357.0,2026,04/04/2026 03:58:05 PM,41.821457,-87.610908,"(41.821456863, -87.610907852)"
4,14155860,JK204251,03/28/2026 12:00:00 AM,020XX E 72ND ST,0460,BATTERY,SIMPLE,STREET,False,False,...,5.0,43.0,08B,NaN,NaN,2026,04/04/2026 03:58:05 PM,NaN,NaN,NaN

In [15]:
df.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [9]:
df=df.dropna(subset=['X Coordinate'])

In [10]:
df=df.dropna(subset=['Ward'])

In [11]:
df=df.dropna(subset=['Community Area'])

In [12]:
df=df.dropna(subset=['Location Description'])

In [16]:
df.shape

(538842, 22)

In [8]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='str')

In [17]:
df=df.head(500000)

In [19]:
df.shape

(500000, 22)

In [20]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14151264,JK198186,03/28/2026 12:00:00 AM,026XX N EMMETT ST,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,...,35.0,22.0,06,1154412.0,1917923.0,2026,04/04/2026 03:58:05 PM,41.930605,-87.707987,"(41.930605381, -87.707987093)"
1,14150705,JK197983,03/28/2026 12:00:00 AM,026XX E 78TH ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,7.0,43.0,14,1194996.0,1853754.0,2026,04/04/2026 03:58:05 PM,41.753614,-87.560973,"(41.753614382, -87.560973062)"
2,14154257,JK202214,03/28/2026 12:00:00 AM,011XX S CENTRAL PARK AVE,0498,BATTERY,"AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SE...",APARTMENT,False,True,...,24.0,29.0,04B,1152552.0,1894695.0,2026,04/04/2026 03:58:05 PM,41.866903,-87.715437,"(41.866902523, -87.715436986)"
3,14150115,JK197373,03/28/2026 12:00:00 AM,006XX E 40TH ST,0920,MOTOR VEHICLE THEFT,ATTEMPT - AUTOMOBILE,STREET,False,False,...,4.0,38.0,07,1181163.0,1878357.0,2026,04/04/2026 03:58:05 PM,41.821457,-87.610908,"(41.821456863, -87.610907852)"
5,14149655,JK196703,03/28/2026 12:00:00 AM,048XX S DREXEL BLVD,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,4.0,39.0,08B,1183004.0,1873073.0,2026,04/04/2026 03:58:05 PM,41.806914,-87.604319,"(41.806914497, -87.604318647)"

In [21]:
df['IUCR'].value_counts()

IUCR
0486    39875
0820    34601
0460    31874
0810    31711
1320    30209
        ...
2094        1
1715        1
1530        1
0272        1
2080        1
Name: count, Length: 352, dtype: int64

In [22]:
cols = [
'ID','Date','Primary Type','Description',
'Location Description','Arrest','Domestic',
'District','Ward','Community Area',
'Latitude','Longitude'
]

df = df[cols]

In [23]:
df['Date'] = pd.to_datetime(df['Date'])

/var/folders/33/6j7x5yjn4vs9rpp5_xx32x740000gn/T/ipykernel_1425/2394721818.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])

-- Date column Feature engineering

In [24]:
df['hour'] = df['Date'].dt.hour
df['day'] = df['Date'].dt.day_name()
df['month'] = df['Date'].dt.month
df['year'] = df['Date'].dt.year
df['weekend'] = df['Date'].dt.dayofweek >= 5

In [25]:
df.shape

(500000, 17)

In [26]:
df.to_csv('data/cleaned_crime_records.csv', index=False)